account/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('password-reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('register/', views.register, name='register'),
    path('profile/', views.profile, name='profile'),
    path('notifications/', views.notifications_list, name='notifications'),
    path('notifications/<str:unread>/', views.notifications_list, name='notifications_unread'),
    path('notification/<int:notification_id>/', views.notification_detail, name='notification_detail'),
    path('tickets/', views.tickets_list, name='tickets_list'),
    path('tickets/add/', views.tickets_add, name='tickets_add'),
    path('ticket/<int:ticket_id>/', views.ticket_detail, name='ticket_detail'),
    path('subscribe/', views.subscribe_list, name='subscribe_list'),
    path('subscribe/add/', views.subscribe_add, name='subscribe_add'),
]

fixigo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('page.urls', namespace='page')),
    path('account/', include('account.urls')),
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

page/urls.py
from django.urls import path
from . import views

app_name = 'page'

urlpatterns = [
    path('', views.home, name='home'),
]

account/models.py
from django.db import models
from django.contrib.auth import get_user_model
import datetime

User = get_user_model()


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name='Пользователь')
    fullname = models.CharField(max_length=200, verbose_name='ФИО', blank=True, null=True)
    phone = models.CharField(max_length=30, verbose_name='Телефон', blank=True, null=True)
    city = models.CharField(max_length=50, verbose_name='Город', blank=True, null=True)
    street = models.CharField(max_length=200, verbose_name='Улица', blank=True, null=True)
    house = models.CharField(max_length=10, verbose_name='Дом', blank=True, null=True)
    apartment = models.PositiveSmallIntegerField(verbose_name='Квартира', blank=True, null=True)

    def __str__(self):
        return f'Профиль {self.fullname}'

    class Meta:
        verbose_name = 'Профиль'
        verbose_name_plural = 'Профили'


class Subscription(models.Model):
    STATUS_CHOICES = (
        ('active', 'Активный'),
        ('archive', 'Архивный'),
        ('waiting_for_pay', 'В ожидании оплаты'),
        ('pending', 'В процессе активации')
    )
    TIME_CHOICES = (
        ('month', 'Месяц'),
        ('year', 'Год')
    )
    title = models.CharField(max_length=150, verbose_name='Название')
    timedelta = models.CharField(max_length=10, verbose_name='Продолжительность', choices=TIME_CHOICES)
    profile = models.ForeignKey(Profile, related_name='subscribtions', verbose_name='Профиль', on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True, verbose_name='Создано')
    price = models.IntegerField(verbose_name='Цена')
    paid = models.BooleanField(default=False, verbose_name='Оплачено?')
    begin = models.DateTimeField(blank=True, null=True, verbose_name='Дата начала')
    end = models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания')
    status = models.CharField(verbose_name='Статус', max_length=20, choices=STATUS_CHOICES)

    def status_verbose(self):
        return dict(self.STATUS_CHOICES)[self.status]

    def days_left(self):
        if self.end:
            days_left = (datetime.date(year=self.end.year, month=self.end.month, day=self.end.day)
                         - datetime.date.today()).days
            if days_left > 0:
                return days_left
        return False

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Подписка'
        verbose_name_plural = 'Подписки'
        ordering = ('-created', '-begin',)

account/views.py
from django.shortcuts import render, redirect, get_object_or_404
from . import forms
from .models import Profile
from notification.models import Notification
from ticket.models import Ticket
from django.contrib.auth import authenticate, login
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.urls import reverse
from .models import Subscription
import requests
from .utils import register_order


def user_login(request):
    if request.user.is_authenticated:
        return redirect('profile')
    if request.method == 'POST':
        login_form = forms.LoginForm(request.POST)
        if login_form.is_valid():
            cd = login_form.cleaned_data
            user = authenticate(request,
                                username=cd['email'],
                                password=cd['password'])
            remember = cd['remember']
            if user is not None:
                if user.is_active:
                    login(request, user)
                    if not remember:
                        request.session.set_expiry(0)
                    return redirect('profile')
                else:
                    messages.warning(request, 'Ваш аккаунт был отключен')
            else:
                messages.error(request, 'Вы ввели неправильный логин или пароль')
    else:
        login_form = forms.LoginForm()
    return render(request, 'registration/login.html', {'login_form': login_form})


def register(request):
    if request.user.is_authenticated:
        return redirect('profile')
    if request.method == 'POST':
        register_form = forms.RegistrationForm(request.POST)
        profile_form = forms.ProfileForm(request.POST)
        if register_form.is_valid() and profile_form.is_valid():
            user = register_form.save(commit=False)
            user.set_password(register_form.cleaned_data['password'])
            user.username = user.email
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            profile.save()
            return render(request, 'registration/register_done.html', {'user': user})
        else:
            messages.error(request, 'Исправьте, пожалуйста, ошибки формы')
    else:
        register_form = forms.RegistrationForm()
        profile_form = forms.ProfileForm()
    return render(request, 'registration/register.html',
                  {'register_form': register_form,
                   'profile_form': profile_form})


@login_required
def profile(request):
    user = request.user
    profile = get_object_or_404(Profile, user=user)
    if request.method == 'POST':
        password_change_form = forms.PasswordChangeForm(data=request.POST, request=request)
        profile_form = forms.ProfileForm(data=request.POST, instance=profile)
        if password_change_form.is_valid() and profile_form.is_valid():
            profile_form.save()
            cd = password_change_form.cleaned_data
            if cd['password']:
                user.set_password(cd['password'])
                user.save()
                re_user = authenticate(request,
                                       username=user.email,
                                       password=cd['password'])
                login(request, re_user)

            if password_change_form.has_changed() or profile_form.has_changed():
                messages.info(request, 'Ваши данные успешно обновлены')
        else:
            messages.error(request, 'Исправьте, пожалуйста, ошибки формы')
    else:
        password_change_form = forms.PasswordChangeForm(request=request)
        profile_form = forms.ProfileForm(instance=profile)

    breadcrumbs = [
        {
            'link': False,
            'label': 'Профиль'
        }
    ]
    context = {
        'section': 'profile',
        'password_change_form': password_change_form,
        'profile_form': profile_form,
        'breadcrumbs': breadcrumbs
    }
    return render(request, 'account/profile.html', context)


@login_required
def notifications_list(request, unread=None):
    profile_obj = request.user.profile
    if unread == 'unread':
        notifications_object = Notification.unread.filter(profile=profile_obj)
    else:
        notifications_object = Notification.objects.filter(profile=profile_obj)
    paginator = Paginator(notifications_object, 10)
    page = request.GET.get('page')
    try:
        notifications = paginator.page(page)
    except PageNotAnInteger:
        notifications = paginator.page(1)
    except EmptyPage:
        notifications = paginator.page(paginator.num_pages)

    breadcrumbs = [
        {
            'link': False,
            'label': 'Уведомления'
        }
    ]
    context = {
        'notifications': notifications,
        'section': 'notifications',
        'unread': unread,
        'breadcrumbs': breadcrumbs
    }
    return render(request, 'account/notifications.html', context)


@login_required
def notification_detail(request, notification_id):
    notification = get_object_or_404(Notification, pk=notification_id, profile=request.user.profile)
    if notification.status == 'unread':
        notification.status = 'read'
        notification.save()

    breadcrumbs = [
        {
            'link': reverse('notifications'),
            'label': 'Уведомления'
        },
        {
            'link': False,
            'label': notification.title
        }
    ]
    context = {
        'notification': notification,
        'section': 'notifications',
        'breadcrumbs': breadcrumbs,
    }
    return render(request, 'account/notification_detail.html', context)


@login_required
def tickets_list(request):
    profile_obj = request.user.profile
    tickets_object = Ticket.objects.filter(profile=profile_obj).order_by('-created')
    paginator = Paginator(tickets_object, 10)
    page = request.GET.get('page')
    try:
        tickets = paginator.page(page)
    except PageNotAnInteger:
        tickets = paginator.page(1)
    except EmptyPage:
        tickets = paginator.page(paginator.num_pages)

    breadcrumbs = [
        {
            'link': False,
            'label': 'Мои заявки'
        }
    ]
    context = {
        'section': 'tickets',
        'tickets': tickets,
        'breadcrumbs': breadcrumbs
    }
    return render(request, 'account/tickets.html', context)


@login_required
def ticket_detail(request, ticket_id):
    profile_obj = request.user.profile
    ticket = get_object_or_404(Ticket, pk=ticket_id, profile=profile_obj)

    breadcrumbs = [
        {
            'link': reverse('tickets_list'),
            'label': 'Мои заявки'
        },
        {
            'link': False,
            'label': ticket.subject
        }
    ]
    context = {
        'section': 'tickets',
        'ticket': ticket,
        'breadcrumbs': breadcrumbs
    }
    return render(request, 'account/ticket_detail.html', context)


@login_required
def tickets_add(request):
    profile_obj = request.user.profile
    if request.method == 'POST':
        ticket_form = forms.TicketForm(data=request.POST)
        if ticket_form.is_valid():
            ticket = ticket_form.save(commit=False)
            ticket.profile = profile_obj
            ticket.save()
            messages.info(request, 'Ваша заявка успешно создана')
            return redirect('tickets_list')
        else:
            messages.error(request, 'Исправьте, пожалуйста, ошибки формы')
    else:
        ticket_form = forms.TicketForm(initial={
            'phone': profile_obj.phone,
            'city': profile_obj.city,
            'street': profile_obj.street,
            'house': profile_obj.house,
            'apartment': profile_obj.apartment
        })
    breadcrumbs = [
        {
            'link': reverse('tickets_list'),
            'label': 'Мои заявки'
        },
        {
            'link': False,
            'label': 'Новая заявка'
        }
    ]
    context = {
        'section': 'tickets',
        'ticket_form': ticket_form,
        'breadcrumbs': breadcrumbs
    }
    return render(request, 'account/ticket_add.html', context)


@login_required
def subscribe_list(request):
    breadcrumbs = [
        {
            'link': False,
            'label': 'Мои подписки'
        }
    ]
    profile = Profile.objects.get(user=request.user)
    subscriptions_obj = Subscription.objects.filter(paid=True, profile=profile)
    paginator = Paginator(subscriptions_obj, 10)
    page = request.GET.get('page')
    try:
        subscriptions = paginator.page(page)
    except PageNotAnInteger:
        subscriptions = paginator.page(1)
    except EmptyPage:
        subscriptions = paginator.page(paginator.num_pages)

    context = {
        'subscriptions': subscriptions,
        'section': 'subscribe',
        'breadcrumbs': breadcrumbs
    }
    return render(request, 'account/subscribe.html', context)


@login_required
def subscribe_add(request):

    if request.method == 'POST':
        subscribe_form = forms.SubscribeForm(request.POST)
        if subscribe_form.is_valid():
            cd = subscribe_form.cleaned_data
            subscribtion = Subscription()
            rate = cd['rate']
            subscribtion.title = rate.title
            subscribtion.timedelta = cd['period']
            if cd['period'] == 'month':
                subscribtion.price = rate.price_month
            else:
                subscribtion.price = rate.price_year
            subscribtion.profile = request.user.profile
            subscribtion.paid = False
            subscribtion.status = 'waiting_for_pay'
            subscribtion.save()
            # register_order(subscribtion.price)
            # ...
        else:
            messages.error(request, 'Выберите тарифный план и срок из списка')
    else:
        subscribe_form = forms.SubscribeForm()
    breadcrumbs = [
        {

account/templates/partials/account_sidebar.html
<div class="personal__sidebar">
    <button class="close__sidebar">
        <svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M1 1L19 19" stroke="white" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
            <path d="M1 19L19 1" stroke="white" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
        </svg>
    </button>
    <h1 class="personal__title">Профиль</h1>
    <ul class="personal__menu">
        <li class="personal__link personal__link_profile{% if section == 'profile' %} current__item{% endif %}">
            <a href="{% url 'profile' %}">
                <svg class="me-2" width="22" height="22" viewBox="0 0 22 22" fill="none"
                     xmlns="http://www.w3.org/2000/svg">
                    <path class="user__path"
                          d="M11 21.7422C5.07719 21.7422 0.257812 16.9228 0.257812 11C0.257812 5.0765 5.07719 0.257812 11 0.257812C16.9228 0.257812 21.7422 5.0765 21.7422 11C21.7422 16.9228 16.9228 21.7422 11 21.7422Z"
                          fill="#ffffff" />
                    <path class="user__path"
                          d="M11 0.515625C16.7812 0.515625 21.4844 5.21881 21.4844 11C21.4844 16.7812 16.7812 21.4844 11 21.4844C5.21881 21.4844 0.515625 16.7812 0.515625 11C0.515625 5.21881 5.21881 0.515625 11 0.515625ZM11 0C4.92456 0 0 4.92456 0 11C0 17.0748 4.92456 22 11 22C17.0754 22 22 17.0748 22 11C22 4.92456 17.0754 0 11 0Z"
                          fill="#ffffff" />
                    <path class="svg__user" fill-rule="evenodd" clip-rule="evenodd"
                          d="M16.3326 13.6963C15.9257 13.0761 15.0518 12.6066 13.3109 11.6711L13.1299 11.5738L11.0269 13.6958C10.9715 13.7517 10.8961 13.7831 10.8175 13.7832C10.8174 13.7832 10.8172 13.7832 10.8171 13.7832C10.7387 13.7832 10.6633 13.752 10.6079 13.6963L8.49399 11.5735C8.32171 11.6659 8.1573 11.7536 8.00033 11.8375C6.40926 12.687 5.61067 13.1135 5.2443 13.707C4.88039 14.2964 4.88367 15.1553 4.89029 16.8663C4.89066 16.9456 4.89092 17.0266 4.89123 17.1093H16.7406C16.7403 17.0293 16.7401 16.9511 16.7399 16.8744C16.735 15.1642 16.7325 14.3058 16.3326 13.6963ZM10.8116 15.715C10.4993 15.715 10.2459 15.4628 10.2459 15.1519C10.2459 14.8408 10.4993 14.5885 10.8116 14.5885C11.1242 14.5885 11.3775 14.8409 11.3775 15.1519C11.3776 15.4628 11.1242 15.715 10.8116 15.715Z"
                          fill="white" />
                    <path class="svg__user" fill-rule="evenodd" clip-rule="evenodd"
                          d="M10.8663 11.6213C12.6622 11.6213 13.6418 8.95345 13.6418 7.58281C13.6418 6.09742 12.3968 4.88892 10.8663 4.88892C9.33564 4.88892 8.09033 6.09742 8.09033 7.58281C8.0904 8.95345 9.07015 11.6213 10.8663 11.6213Z"
                          fill="white" />
                </svg>
                Профиль
            </a>
        </li>
        <li class="personal__link{% if section == 'subscribe' %} current__item{% endif %}">
            <a href="{% url 'subscribe_list' %}">
                Мои подписки
            </a>
        </li>
        <li class="personal__link{% if section == 'notifications' %} current__item{% endif %}">
            <a href="{% url 'notifications' %}">
                Уведомления
                {% if notifications_count %}
                    <span class="count__message ms-1">({{ notifications_count }})</span>
                {% endif %}
            </a>

        </li>
        <li class="personal__link{% if section == 'tickets' %} current__item{% endif %}">
            <a href="{% url 'tickets_list' %}">
                Мои заявки
            </a>
        </li>
        <li class="personal__link personal__link_exit">
            <a href="{% url 'logout' %}">
                <svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M7.5 17.5H4.16667C3.72464 17.5 3.30072 17.3244 2.98816 17.0118C2.67559 16.6993 2.5 16.2754 2.5 15.8333V4.16667C2.5 3.72464 2.67559 3.30072 2.98816 2.98816C3.30072 2.67559 3.72464 2.5 4.16667 2.5H7.5"
                          stroke="white" stroke-linecap="round" stroke-linejoin="round" />
                    <path d="M13.3335 14.1668L17.5002 10.0002L13.3335 5.8335" stroke="white" stroke-linecap="round"
                          stroke-linejoin="round" />
                    <path d="M17.5 10H7.5" stroke="white" stroke-linecap="round" stroke-linejoin="round" />
                </svg>
                Выйти
            </a>
        </li>
    </ul>
</div>

account/templates/partials/archive_notification.html
<li{% if notification.status == 'read' %} class="message__list_read"{% endif %}>
    <div class="message__icon"></div>
    <a href="{{ notification.get_absolute_url }}" class="message__link">
        {{ notification.title }}
    </a>
    <p class="message__date">
        {{ notification.publish|date:'d.m.Y' }}
    </p>
</li>

account/templates/partials/archive_ticket.html
<tr>
    <td>{{ ticket.created|date:'d.m.Y' }}</td>
    <td>
        <a href="{{ ticket.get_absolute_url }}" class="ticket__link">
            {{ ticket.subject }}
        </a>
    </td>
    <td>{{ ticket.status }}</td>
</tr>

account/templates/partials/breadcrumbs.html
{% load static %}

<div class="breadcrumbs pb_70">
    <span>
        <a href="{% url 'page:home' %}">
            <span>Главная</span>
        </a>
    </span>
    {% for breadcrumb in breadcrumbs %}
        <img src="{% static '/img/menu_doted.svg' %}" alt="точка">
        <span>
            {% if breadcrumb.link %}
                <a href="{{ breadcrumb.link }}" class="post post-page">
                    <span>
                        {{ breadcrumb.label }}
                    </span>
                </a>
            {% else %}
                <span class="post post-page current-item">
                    {{ breadcrumb.label }}
                </span>
            {% endif %}
        </span>
    {% endfor %}
    &nbsp;

</div>

account/templates/partials/form_messages.html
{% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li class="messages__item{% if message.tags %} {{ message.tags }}"{% endif %}>
                {{ message }}
            </li>
        {% endfor %}
    </ul>
{% endif %}

account/templates/partials/pagination.html
{% if page.paginator.num_pages > 1 %}
    <div class="message__pagination d-flex mt_30">
        {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number }}" class="pag__link pag__link_prev">
                <svg width="49" height="41" viewBox="0 0 49 41" fill="none"
                    xmlns="http://www.w3.org/2000/svg">
                    <path
                        d="M37.9268 20.5006L48.6395 2.29049C48.8789 1.8829 48.8326 1.36747 48.5231 1.00948C48.2147 0.649336 47.7101 0.528567 47.2733 0.705406L0.898348 19.4762C0.481059 19.6466 0.208252 20.0499 0.208252 20.5006C0.208252 20.9513 0.481059 21.3546 0.898348 21.525L47.2733 40.2958C47.4071 40.3497 47.5483 40.3756 47.6874 40.3756C48.0012 40.3756 48.3096 40.2419 48.5231 39.9917C48.8326 39.6338 48.8789 39.1183 48.6395 38.7107L37.9268 20.5006ZM34.8644 25.079L35.6106 27.6087L22.8437 22.1569L34.8644 25.079ZM35.5416 19.3964L19.6002 19.9485L35.5416 14.3846V19.3964Z"
                        fill="url(#paint0_linear_60_463)" />
                    <defs>
                        <linearGradient id="paint0_linear_60_463" x1="47.262" y1="40.375" x2="-2.07746"
                            y2="37.3003" gradientUnits="userSpaceOnUse">
                            <stop class="stop_1" stop-color="#303C42" />
                            <stop class="stop_2" offset="1" stop-color="#303C42" />
                        </linearGradient>
                    </defs>
                </svg>
            </a>
        {% endif %}
        <span class="pag__link">Страница {{ page.number }} из {{ page.paginator.num_pages }}</span>
        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}" class="pag__link pag__link_next">
                <svg width="49" height="41" viewBox="0 0 49 41" fill="none"
                    xmlns="http://www.w3.org/2000/svg">
                    <path
                        d="M11.073 20.4994L0.360206 38.7095C0.120827 39.1171 0.16719 39.6325 0.476662 39.9905C0.785049 40.3507 1.28969 40.4714 1.72641 40.2946L48.1014 21.5238C48.5187 21.3534 48.7915 20.9501 48.7915 20.4994C48.7915 20.0487 48.5187 19.6454 48.1014 19.475L1.72641 0.704182C1.59269 0.650269 1.45143 0.62439 1.31233 0.62439C0.998547 0.62439 0.690159 0.758099 0.476658 1.00826C0.167187 1.36625 0.120823 1.88167 0.360203 2.28927L11.073 20.4994ZM14.1353 15.921L13.3892 13.3913L26.1561 18.8431L14.1353 15.921ZM13.4582 21.6036L29.3996 21.0515L13.4582 26.6154L13.4582 21.6036Z"
                        fill="url(#paint0_linear_60_464)"></path>
                    <defs>
                        <linearGradient id="paint0_linear_60_464" x1="47.262" y1="40.375" x2="-2.07746"
                            y2="37.3003" gradientUnits="userSpaceOnUse">
                            <stop class="stop_1" stop-color="#303C42"></stop>
                            <stop class="stop_2" offset="1" stop-color="#303C42"></stop>
                        </linearGradient>
                    </defs>
                </svg>
            </a>
        {% endif %}
    </div>
{% endif %}

account/templates/partials/single_notification.html
<div class="message__title">
    <div class="message__icon"></div>
    <p class="message__link">
        {{ notification.title }}
    </p>
    <p class="message__date">
        {{ notification.publish|date:'d.m.Y' }}
    </p>
</div>
<div class="message__content">
    <div>
        {{ notification.body|linebreaks }}
    </div>
</div>

account/templates/partials/single_ticket.html
<div class="ticket__title">
    <p class="ticket__date ">
        {{ ticket.created|date:'d.m.Y' }}
    </p>
    <p class="ticket__link">
        {{ ticket.subject }}
    </p>
</div>
<div class="ticket__content">
    <div>
        {{ ticket.body|linebreaks }}
    </div>
</div>